/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allgo_web_jni_RealJNI */

#ifndef _Included_com_allgo_web_jni_RealJNI
#define _Included_com_allgo_web_jni_RealJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_allgo_web_jni_RealJNI
 * Method:    updateRealCheg
 * Signature: ([Lcom/allgo/web/packet/RealCheg;)V
 */
JNIEXPORT void JNICALL Java_com_allgo_web_jni_RealJNI_updateRealCheg
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_allgo_web_jni_RealJNI
 * Method:    updateRealProgram
 * Signature: ([Lcom/allgo/web/packet/RealProgram;)V
 */
JNIEXPORT void JNICALL Java_com_allgo_web_jni_RealJNI_updateRealProgram
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
