/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allgo_web_jni_TestJni */

#ifndef _Included_com_allgo_web_jni_TestJni
#define _Included_com_allgo_web_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_allgo_web_jni_TestJni
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_allgo_web_jni_TestJni_printHello
  (JNIEnv *, jobject);

/*
 * Class:     com_allgo_web_jni_TestJni
 * Method:    printString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_allgo_web_jni_TestJni_printString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
