#!/bin/bash

gcc -I/Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/Home/include/darwin -fPIC -c testjni.c

gcc -I/Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/Home/include/darwin -fPIC -c RealJNI.c
