


all : 
	gcc chk_redis.c -o chk_redis -I /usr/local/include/hiredis/ -lhiredis
	gcc test.c -o test -I /usr/local/include/hiredis/ -lhiredis
	gcc chk_stock.c -o chk_stock -I /usr/local/include/hiredis/ -lhiredis
